name: Fuzz test

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  Fuzz-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable  

      - name: Copy tester script
        run: |
          if [ ! -f run_fuzz_tests.sh ]; then
            echo "run_fuzz_tests.sh not found!"
            exit 1
          fi
          chmod +x run_fuzz_tests.sh

      - name: Run fuzz tests
        run: |
          echo "Starting run_fuzz_tests.sh..."
          ./run_fuzz_tests.sh
          echo "Fuzz test completed."