name: gitleaks
on: [pull_request, push, workflow_dispatch]

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: true
      - name: Run Gitleaks scan
        uses: ./.github/actions/security/gitleaks
        with:
          scan-scope: "all"
          source: "./"
          config_path: "./ci/gitleaks_baselines/os-image-composer-gitleaks.csv"
          report_format: "csv"
          redact: "true"